"""empty message

Revision ID: 4b9b022515dd
Revises: a3d49c2a8950
Create Date: 2019-02-07 12:12:17.020372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9b022515dd'
down_revision = 'a3d49c2a8950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('uid', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_from', sa.String(length=150), nullable=False),
    sa.Column('email_to', sa.String(length=150), nullable=False),
    sa.Column('subject', sa.String(length=190), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=190), nullable=False),
    sa.Column('phone', sa.String(length=190), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_uid'), 'emails', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_uid'), table_name='emails')
    op.drop_table('emails')
    # ### end Alembic commands ###
