"""empty message

Revision ID: 57aa6c862412
Revises: 1dc5d9b3886e
Create Date: 2019-02-07 11:06:06.530455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57aa6c862412'
down_revision = '1dc5d9b3886e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('percent', sa.Integer(), nullable=True))
    op.add_column('skills', sa.Column('techno', sa.String(length=190), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'techno')
    op.drop_column('skills', 'percent')
    # ### end Alembic commands ###
