"""empty message

Revision ID: 5f6c0b999b70
Revises: 4b9b022515dd
Create Date: 2019-02-07 12:45:41.917137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f6c0b999b70'
down_revision = '4b9b022515dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'emails', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_column('emails', 'user_id')
    # ### end Alembic commands ###
