"""empty message

Revision ID: a35c50888cf0
Revises: d8d042eaf14c
Create Date: 2019-01-30 20:09:41.296652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35c50888cf0'
down_revision = 'd8d042eaf14c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('educations', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('hobbies', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('services', sa.Column('detail', sa.Text(), nullable=True))
    op.add_column('services', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('skills', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('works', sa.Column('image', sa.String(length=190), nullable=True))
    op.add_column('works', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('works', sa.Column('url', sa.String(length=190), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'url')
    op.drop_column('works', 'published')
    op.drop_column('works', 'image')
    op.drop_column('users', 'published')
    op.drop_column('skills', 'published')
    op.drop_column('services', 'published')
    op.drop_column('services', 'detail')
    op.drop_column('jobs', 'published')
    op.drop_column('hobbies', 'published')
    op.drop_column('educations', 'published')
    op.drop_column('activities', 'published')
    # ### end Alembic commands ###
