"""empty message

Revision ID: a3d49c2a8950
Revises: 57aa6c862412
Create Date: 2019-02-07 11:32:44.444203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d49c2a8950'
down_revision = '57aa6c862412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('category', sa.String(length=190), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'category')
    # ### end Alembic commands ###
