"""empty message

Revision ID: a5b92767d130
Revises: 40010098a0a6
Create Date: 2019-01-28 11:30:49.130092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5b92767d130'
down_revision = '40010098a0a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('linkedin', sa.String(length=150), nullable=True))
    op.drop_column('users', 'youtube')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('youtube', mysql.VARCHAR(length=150), nullable=True))
    op.drop_column('users', 'linkedin')
    # ### end Alembic commands ###
