"""empty message

Revision ID: ccac6db519ad
Revises: 
Create Date: 2019-01-31 12:41:41.617270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ccac6db519ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('educations', sa.Column('begin_at', sa.DateTime(), nullable=True))
    op.add_column('educations', sa.Column('end_at', sa.DateTime(), nullable=True))
    op.drop_column('educations', 'begin')
    op.drop_column('educations', 'end')
    op.add_column('jobs', sa.Column('begin_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('end_at', sa.DateTime(), nullable=True))
    op.drop_column('jobs', 'begin')
    op.drop_column('jobs', 'end')
    op.add_column('works', sa.Column('image', sa.String(length=190), nullable=True))
    op.add_column('works', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('works', sa.Column('url', sa.String(length=190), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'url')
    op.drop_column('works', 'published')
    op.drop_column('works', 'image')
    op.add_column('jobs', sa.Column('end', mysql.DATETIME(), nullable=True))
    op.add_column('jobs', sa.Column('begin', mysql.DATETIME(), nullable=True))
    op.drop_column('jobs', 'end_at')
    op.drop_column('jobs', 'begin_at')
    op.add_column('educations', sa.Column('end', mysql.DATETIME(), nullable=True))
    op.add_column('educations', sa.Column('begin', mysql.DATETIME(), nullable=True))
    op.drop_column('educations', 'end_at')
    op.drop_column('educations', 'begin_at')
    # ### end Alembic commands ###
