"""empty message

Revision ID: df2e5edc74a0
Revises: 5f6c0b999b70
Create Date: 2019-02-07 13:22:17.345230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df2e5edc74a0'
down_revision = '5f6c0b999b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('folder', sa.String(length=50), nullable=True))
    op.add_column('emails', sa.Column('read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'read')
    op.drop_column('emails', 'folder')
    # ### end Alembic commands ###
