"""empty message

Revision ID: f97a3af2ccaa
Revises: 
Create Date: 2019-01-26 14:33:52.488445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97a3af2ccaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('job', sa.String(length=60), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=130), nullable=True),
    sa.Column('photo', sa.String(length=130), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('facebook', sa.String(length=150), nullable=True),
    sa.Column('github', sa.String(length=150), nullable=True),
    sa.Column('youtube', sa.String(length=150), nullable=True),
    sa.Column('twitter', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('photo')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)
    op.create_table('educations',
    sa.Column('uid', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formation', sa.String(length=190), nullable=False),
    sa.Column('location', sa.String(length=190), nullable=False),
    sa.Column('school', sa.String(length=190), nullable=False),
    sa.Column('begin', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_educations_uid'), 'educations', ['uid'], unique=True)
    op.create_table('jobs',
    sa.Column('uid', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=190), nullable=False),
    sa.Column('location', sa.String(length=190), nullable=False),
    sa.Column('company', sa.String(length=190), nullable=False),
    sa.Column('begin', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_uid'), 'jobs', ['uid'], unique=True)
    op.create_table('services',
    sa.Column('uid', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=190), nullable=False),
    sa.Column('icon', sa.String(length=190), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_uid'), 'services', ['uid'], unique=True)
    op.create_table('skills',
    sa.Column('uid', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(length=190), nullable=False),
    sa.Column('level', sa.String(length=190), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('percent', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_uid'), 'skills', ['uid'], unique=True)
    op.create_table('works',
    sa.Column('uid', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=190), nullable=False),
    sa.Column('techno', sa.String(length=190), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_works_uid'), 'works', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_works_uid'), table_name='works')
    op.drop_table('works')
    op.drop_index(op.f('ix_skills_uid'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_services_uid'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_jobs_uid'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_educations_uid'), table_name='educations')
    op.drop_table('educations')
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
